/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Font;

/**
 *
 * @author stivenSP
 */
public class ejmJslider extends javax.swing.JFrame {

    /**
     * Creates new form ejmJslider
     */
    public ejmJslider() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicio();
    }
    private void inicio(){
        //-Establecemos propiedades para el JTextArea-
        //Establecemos tipo de fuente Consolas, texto plano, tamaño 15
        jt.setFont(new Font("Consolas", Font.PLAIN, 16));
        //Especificamos que el texto se ajusta al tamaño del Área de texto
        jt.setLineWrap(true);
        jt.setWrapStyleWord(true);
        //Agregamos texto simple al Área de Texto como ejemplo.
        //El indicador \n sirve para salto de línea.
        jt.setText("Java Development Kit o (JDK), es un "
                + "software que provee herramientas de desarrollo "
                + "para la creación de programas en Java. "
                + "\nNetBeans IDE. Es un entorno de desarrollo integrado libre, "
                + "hecho principalmente para el lenguaje de programación Java."); 
        
        //Configurams el JSlider
        //Valor mínimo
        jl.setMinimum(1);
        //Valor máximo
        jl.setMaximum(5);
        //valor inicial
        jl.setValue(16);
        //Valores para mostrar regla
        //mínimo para mostrar
        jl.setMinorTickSpacing(1);
        //máximo para mostrar
        jl.setMajorTickSpacing(1);
        //Especificamos que se muestren los valores
        jl.setPaintTicks(true);
        jl.setPaintLabels(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl.setOrientation(javax.swing.JSlider.VERTICAL);
        jl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jlStateChanged(evt);
            }
        });

        jt.setColumns(20);
        jt.setRows(5);
        jScrollPane1.setViewportView(jt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jlStateChanged
              //Obtenemos valor del JSlider
        int value = jl.getValue();
        //Indicamos las propiedades de fuente del JTextArea
        //value será la que cambien según se mueva el marcador del JSlider.
        jt.setFont(new Font("Consolas", Font.PLAIN, value));
  
    }//GEN-LAST:event_jlStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejmJslider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejmJslider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejmJslider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejmJslider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejmJslider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jl;
    private javax.swing.JTextArea jt;
    // End of variables declaration//GEN-END:variables
}
