/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ConvertirMayuscula;
import control.Validaciones;
import datos.ConexionBD;
import datos.GetterAndSetter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author stivenSP
 */
public class IU_municipio extends javax.swing.JFrame {

    Validaciones v = new Validaciones();
    GetterAndSetter gys = new GetterAndSetter();
    ConexionBD bd = new ConexionBD();
    
    //este atributo es el que utilice para insertar en la bd
    int cod_municipio;
    boolean esModificarMun=false;
    boolean esModificarVer=false;
    
    public IU_municipio() {
        initComponents();
        this.setLocationRelativeTo(null);
        metodosInicio();
    }
    public void metodosInicio(){
        v.validarSoloLetras(txtVereda);
        v.validarSoloLetras(txtMunicipio);
        v.limitarCaracteres(txtVereda, 40);
        v.limitarCaracteres(txtMunicipio, 50);
        
        txtMunicipio.setDocument(new ConvertirMayuscula());
        txtVereda.setDocument(new ConvertirMayuscula());
        
        btnEliminarMunicipio.setEnabled(false);
        btnGuardarMunicipio.setEnabled(false);
        BtnEliminarVereda.setEnabled(false);
        btnGuardarVereda.setEnabled(false);
        comboMunicipio.setEnabled(false);
        
        llenarListaYtabla();
    }
    public void llenarListaYtabla(){
        bd.llenarListaMunicipio(listaMunicipio);
        comboMunicipio.removeAllItems();
        comboMunicipio.addItem("--SELECCIONAR--");
        bd.llenarListaMunicipio(comboMunicipio);
        bd.llenarTablaMunicipio(tablaMunicipio);
    }
    public void validarIngresoMun(){                
        if(txtMunicipio.getText().trim().isEmpty()){
            btnGuardarMunicipio.setEnabled(false);
        }else{
            btnGuardarMunicipio.setEnabled(true);
        }
    }
    
    //este lo modifique porque no validaba el boton de guardar porque diste copiar y pegar y te olvidaste de cambiarle nombre 
   public void validarIngresoVer(){                
        if(txtVereda.getText().trim().isEmpty()){
            btnGuardarVereda.setEnabled(false);
            comboMunicipio.setEnabled(false);
        }else{
            btnGuardarVereda.setEnabled(true);
            comboMunicipio.setEnabled(true);
        }
    }
    private int getIDvereda(){
        int r=0;
        try {
            Statement stmt = bd.getConexion(gys.getHost(), gys.getNomBD(), gys.getUser(), gys.getPassword()).createStatement();
            ResultSet rs=stmt.executeQuery("select v.idvereda from vereda v where nombre = '"+tablaMunicipio.getValueAt(tablaMunicipio.getSelectedRow(), 1).toString()+"'");
            while(rs.next())
                r = rs.getInt("idvereda");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"error \n" +ex); 
           
        }
        return r;
    }
    private int getIDmunicipio(){
        int r=0;
         try {
            Statement stmt = bd.getConexion(gys.getHost(), gys.getNomBD(), gys.getUser(), gys.getPassword()).createStatement();
            ResultSet rs=stmt.executeQuery("select idmunicipio from municipio  where nombre = '"+tablaMunicipio.getValueAt(tablaMunicipio.getSelectedRow(), 0).toString()+"'");
            while(rs.next())
                r = rs.getInt("idmunicipio");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"error \n" +ex); 
           
        }
        return r;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtVereda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboMunicipio = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMunicipio = new javax.swing.JTable();
        btnGuardarVereda = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BtnEliminarVereda = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMunicipio = new javax.swing.JList();
        btnGuardarMunicipio = new javax.swing.JButton();
        txtMunicipio = new javax.swing.JTextField();
        btnEliminarMunicipio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Municipio");
        setUndecorated(true);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setText("Vereda:");

        txtVereda.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtVeredaCaretUpdate(evt);
            }
        });
        txtVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVeredaActionPerformed(evt);
            }
        });

        jLabel2.setText("Municipio:");

        comboMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMunicipioActionPerformed(evt);
            }
        });

        tablaMunicipio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Municipio", "Vereda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMunicipioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMunicipio);
        if (tablaMunicipio.getColumnModel().getColumnCount() > 0) {
            tablaMunicipio.getColumnModel().getColumn(0).setResizable(false);
        }

        btnGuardarVereda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarVereda.setText("Guardar");
        btnGuardarVereda.setEnabled(false);
        btnGuardarVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVeredaActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton6.setText("Atras");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        BtnEliminarVereda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        BtnEliminarVereda.setText("Eliminar");
        BtnEliminarVereda.setEnabled(false);
        BtnEliminarVereda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarVeredaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(btnGuardarVereda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEliminarVereda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtVereda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVereda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(btnGuardarVereda)
                    .addComponent(BtnEliminarVereda))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vereda", jPanel2);

        listaMunicipio.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMunicipioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaMunicipio);

        btnGuardarMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardarMunicipio.setText("Guardar");
        btnGuardarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMunicipioActionPerformed(evt);
            }
        });

        txtMunicipio.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMunicipioCaretUpdate(evt);
            }
        });

        btnEliminarMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminarMunicipio.setText("Eliminar");
        btnEliminarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMunicipioActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre municipio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardarMunicipio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarMunicipio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarMunicipio)
                            .addComponent(btnGuardarMunicipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Municipio", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtVeredaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtVeredaCaretUpdate
       validarIngresoVer();
    }//GEN-LAST:event_txtVeredaCaretUpdate

    private void txtMunicipioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMunicipioCaretUpdate
        validarIngresoMun();
    }//GEN-LAST:event_txtMunicipioCaretUpdate

    private void btnGuardarVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVeredaActionPerformed
         if(comboMunicipio.getSelectedItem()=="--SELECCIONAR--"){
            JOptionPane.showMessageDialog(null,"SELECCIONE UN MUNICIPIO");
        }else{
        
        
        try {
            if(esModificarVer==false){
                //guardar
                bd.insertarVereda(cod_municipio, txtVereda.getText());
                JOptionPane.showMessageDialog(null, "GUARDADO CORRECTAMENTE");
                llenarListaYtabla();
                txtVereda.setText(null);
            }else{
                //modificar
                bd.modificarVereda(getIDvereda(), txtVereda.getText(), cod_municipio);
                JOptionPane.showMessageDialog(null, "MODIFICADO CORRECTAMENTE");
                llenarListaYtabla();
                txtVereda.setText(null);
            }
            BtnEliminarVereda.setEnabled(false);
            esModificarVer=false;
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"error al guardar vereda" +ex);
        }
      }
    }//GEN-LAST:event_btnGuardarVeredaActionPerformed

    private void btnGuardarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMunicipioActionPerformed
        try {
            if(esModificarMun==false){
                //INSERTAR
                bd.insertarMunicipio(txtMunicipio.getText());
                JOptionPane.showMessageDialog(null, "GUARDADO CORRECTAMENTE");
                llenarListaYtabla();
                txtMunicipio.setText(null);
            }else{
                //MODIFICAR
                bd.modificarMunicipio(cod_municipio, txtMunicipio.getText());
                JOptionPane.showMessageDialog(null, "MODIFICADO CORRECTAMENTE");
                esModificarMun=false;
                llenarListaYtabla();
                txtMunicipio.setText(null);
            }
            btnEliminarMunicipio.setEnabled(false);
            esModificarMun = false;    
            
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,"OCURRIO UN ERROR " +ex);
        }
        
    }//GEN-LAST:event_btnGuardarMunicipioActionPerformed

    private void comboMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMunicipioActionPerformed

        try {
            Statement stmt = bd.getConexion(gys.getHost(), gys.getNomBD(), gys.getUser(), gys.getPassword()).createStatement();
            ResultSet rs=stmt.executeQuery("select m.idmunicipio from municipio m where nombre = '"+this.comboMunicipio.getSelectedItem()+"'");
            while(rs.next())
                cod_municipio=rs.getInt("idmunicipio");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"error aki\n" +ex);   
        }
        
    }//GEN-LAST:event_comboMunicipioActionPerformed

    private void txtVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVeredaActionPerformed
        
    }//GEN-LAST:event_txtVeredaActionPerformed

    private void listaMunicipioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMunicipioMouseClicked
        try {
            if(evt.getClickCount()==2){
                Statement stmt = bd.getConexion(gys.getHost(), gys.getNomBD(), gys.getUser(), gys.getPassword()).createStatement();
                ResultSet rs=stmt.executeQuery("select * from municipio where nombre = '"+this.listaMunicipio.getSelectedValue()+"'");
                rs.next();
                cod_municipio=rs.getInt("idmunicipio");
                txtMunicipio.setText(""+rs.getString("nombre"));
                esModificarMun=true;
                btnEliminarMunicipio.setEnabled(true);
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"error\n" +ex);   
        }
    }//GEN-LAST:event_listaMunicipioMouseClicked

    private void btnEliminarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMunicipioActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este municipio?", "Seleciona una opcion!", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            try {
                bd.eliminarMunicipio(cod_municipio);
                JOptionPane.showMessageDialog(null, "Eliminado correctamente");
                llenarListaYtabla();
                txtMunicipio.setText(null);
                btnEliminarMunicipio.setEnabled(false);
                esModificarMun = false;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar ");
                System.out.println("error al eliminar municipio \n");
            }    
        }
    }//GEN-LAST:event_btnEliminarMunicipioActionPerformed

    private void tablaMunicipioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMunicipioMouseClicked
        if(evt.getClickCount()==2){
            try {
                txtVereda.setText(bd.obtenerVereda(getIDvereda()));
                this.comboMunicipio.setSelectedItem(bd.getNomMunicipio(getIDmunicipio()));
                esModificarVer=true;
                BtnEliminarVereda.setEnabled(true);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al consultar este registro\n"+evt);
            }
        }
    }//GEN-LAST:event_tablaMunicipioMouseClicked

    private void BtnEliminarVeredaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarVeredaActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar esta vereda?", "Seleciona una opcion!", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            try {
                bd.eliminarVereda(getIDvereda());
                JOptionPane.showMessageDialog(null, "Eliminado correctamente");
                llenarListaYtabla();
                txtVereda.setText(null);
                BtnEliminarVereda.setEnabled(false);
                esModificarVer = false;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar ");
                System.out.println("error al eliminar vereda \n");
            }    
        }
    }//GEN-LAST:event_BtnEliminarVeredaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_municipio().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarVereda;
    private javax.swing.JButton btnEliminarMunicipio;
    private javax.swing.JButton btnGuardarMunicipio;
    private javax.swing.JButton btnGuardarVereda;
    private javax.swing.JComboBox comboMunicipio;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listaMunicipio;
    private javax.swing.JTable tablaMunicipio;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtVereda;
    // End of variables declaration//GEN-END:variables
}
